name: cross_platform_airdrop
description: A cross-platform AirDrop-style file sharing app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.1
  file_picker: ^8.0.0
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  shared_preferences: ^2.2.1
  device_info_plus: ^9.1.1
  network_info_plus: ^4.1.0
  uuid: ^4.2.1
  web_socket_channel: ^2.4.0
  dio: ^5.3.3
  shelf: ^1.4.1
  flutter_webrtc: ^0.9.48
  encrypt: ^5.0.1
  pointycastle: ^3.7.3
  open_file: ^3.3.2
  video_thumbnail: ^0.5.3
  image_picker: ^1.0.4
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.3
  flutter_local_notifications: ^16.3.2
  workmanager: ^0.5.2
  background_fetch: ^1.2.1
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  connectivity_plus: ^5.0.2
  nearby_connections: ^3.2.0
  permission_handler: ^11.3.0
  sqflite: ^2.3.0
  path: ^1.8.3
  crypto: ^3.0.3
  dotted_border: ^2.1.0
  haptic_feedback: ^0.5.1
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  sqflite_common_ffi: ^2.3.0
  mockito: ^5.4.4

flutter:
  generate: true
  uses-material-design: true
  
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
