name: cross_platform_airdrop_flutter
description: A cross-platform AirDrop-style file sharing app.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  file_picker: ^8.0.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  network_info_plus: ^4.1.0
  device_info_plus: ^9.1.1
  uuid: ^4.2.1
  http: ^1.1.2
  dio: ^5.4.0
  path_provider: ^2.1.1
  mime: ^1.0.4
  connectivity_plus: ^5.0.2
  web_socket_channel: ^2.4.0  # Added for WebSocket signaling

<<<<<<< HEAD
  # UI and Core Packages
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  # File & Storage
  file_picker: ^8.0.5
  shared_preferences: ^2.2.3

  # Networking & Device Info
  flutter_webrtc: ^0.9.32
  web_socket_channel: ^3.0.0
  permission_handler: ^11.3.1
  network_info_plus: ^5.0.3
  device_info_plus: ^10.1.0
  uuid: ^4.4.0
  
=======
>>>>>>> f12af1b220791c3a97c52939a2dc5fd17d782d2b
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true