name: flutter_airdrop
description: A cross-platform AirDrop-style file sharing app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  file_picker: ^6.1.1
  path: ^1.8.3
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  network_info_plus: ^4.1.0
  device_info_plus: ^9.1.1
  uuid: ^4.2.1
  http: ^1.1.2
  dio: ^5.4.0
  path_provider: ^2.1.1
  mime: ^1.0.4
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true